# Generated by Django 4.2.1 on 2023-05-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='comleted',
            new_name='completed',
        ),
    ]
