# Generated by Django 4.2.1 on 2023-05-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_comleted_todoitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='author',
        ),
    ]
