# Generated by Django 4.2.1 on 2023-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todoitem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('password2', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
