# Generated by Django 4.2.1 on 2023-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auth_alter_todoitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
